### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by JohanChungus** [Erisa/sdxl-worker#1]
TypeError
Fetch API cannot load: /run
TypeError: Fetch API cannot load: /run
    at InferenceSession.run (index.js:2782:36)
    at Ai.run (index.js:2851:42)
    at Object.fetch (index.js:2874:27)

**Comment by Erisa** [comment]
Thanks for the report. It looks like the Workers AI team made a change that resulted in old versions of `@cloudflare/ai` breaking.

Pushing an update that will fix this now.

**Comment by Erisa** [comment]
Should be fixed now, pull the latest changes and give it a go

**Comment by JohanChungus** [comment]
Thank u its working now
